### PR TITLE
Implement score remark Feature based on user score

### PR DESCRIPTION
**Pull request by Adamson123**
Displays a remark and message based on the user’s score percentage, with the remark color-coded according to the score range.

### CODE REVIEW

**Comment by imhardikdesai** [comment]
Thanks @Adamson123 for your valuble contribution, please see attached screenshot which causing fails during deployment build, once this error resolved we will review it and merge it 😃

**Comment by Adamson123** [comment]
Hello @imhardikdesai,  
I've fixed the issue. Please review the changes and let me know if there's anything else that needs attention. Thanks for your response.

**Review by imhardikdesai — APPROVED** [review]
Good job @Adamson123

**Comment by Adamson123** [comment]
Thank you for making my first contribution a great experience 🙌, peace✌

**Comment by imhardikdesai** [comment]
> Thank you for making my first contribution a great experience 🙌, peace✌

Happy to help in your open source journey, wish you the luck for future 👏🍀

**Pull request merged**
